const evaluateAnswer = {
  key: 'evaluate',
  noun: 'Evaluation Result',

  display: {
    label: 'Evaluate Answer',
    description: 'Evaluate the correctness and completeness of a response from an assistant or RAG system.'
  },

  operation: {
    inputFields: [
      {
        key: 'question',
        required: true,
        type: 'text',
        label: 'Question',
        helpText: 'The question for which the answer was generated'
      },
      {
        key: 'answer',
        required: true,
        type: 'text',
        label: 'Generated Answer',
        helpText: 'The answer generated by the assistant or RAG system'
      },
      {
        key: 'ground_truth_answer',
        required: true,
        type: 'text',
        label: 'Ground Truth Answer',
        helpText: 'The correct answer to the question for comparison'
      }
    ],

    perform: (z, bundle) => {
      const body = {
        question: bundle.inputData.question,
        answer: bundle.inputData.answer,
        ground_truth_answer: bundle.inputData.ground_truth_answer
      };

      const promise = z.request({
        method: 'POST',
        url: 'https://prod-1-data.ke.pinecone.io/assistant/evaluation/metrics/alignment',
        headers: {
          'Content-Type': 'application/json'
        },
        body: body
      });

      return promise.then((response) => {
        return [response.json];
      });
    },

    sample: {
      question: 'What are the capital cities of France, England and Spain?',
      answer: 'Paris is the capital city of France, London of England and Madrid of Spain',
      ground_truth_answer: 'Paris is the capital city of France, London of England and Madrid of Spain'
    }
  }
};

module.exports = evaluateAnswer;
